name = "Craftpicx Evolution Prod"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa086c6e835c2756991eae69030e7da936d7f8684564cf062162f1cf11e4b04b"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
