
["Numismatics Utils"]
	#The horizontal offset of the Bank Meter text (in pixels)
	#Default is 2.
	hud_x_position = 2
	#The vertical offset of the Bank Meter text (in pixels)
	#Default is 2.
	hud_y_position = 2
	#The scale of the Bank Meter text.
	#Default is 1.0.
	#Range: 0.5 ~ 10.0
	hud_scale = 1.0

