
[client]

	[client.rendering]
		#Render ships with batch rendering mode?
		doBatchRendering = true

	[client.ship]
		#Should terminal be visible while piloted?
		terminalVisibleWhilePiloted = false
		#Should the helicopter make a hover sound?
		helicopterHoverSound = true
		#Use older & shorter hover sound loop?
		useOldHelicopterHoverSound = false
		#Volume to use for helicopter hover sound
		#Range: 0.0 ~ 150.0
		helicopterHoverSoundVolume = 100.0
		#Volume to use for engine sound
		#Range: 0.0 ~ 150.0
		engineSoundVolume = 100.0
		#Should terminal be interactive while piloted?
		terminalInteractiveWhilePiloted = false
		#Volume to use for drill sound
		#Range: 0.0 ~ 150.0
		drillSoundVolume = 100.0
		#Volume to use for buzzsaw sound
		#Range: 0.0 ~ 150.0
		buzzsawSoundVolume = 100.0

